run:
  modules-download-mode: readonly
  tests: true
linters:
  enable-all: true
  disable:
    - asasalint
    - containedctx
    - cyclop
    - execinquery
    - exhaustruct
    - forcetypeassert
    - funlen
    - gocognit
    - godox
    - err113
    - gochecknoglobals
    - gochecknoinits
    - gocyclo
    - gofmt
    - goimports
    - gomnd
    - importas
    - interfacebloat
    - ireturn
    - maintidx
    - makezero
    - mnd
    - nestif
    - nlreturn
    - nonamedreturns
    - nosprintfhostport
    - paralleltest
    - prealloc
    - tagliatelle
    - testpackage
    - varnamelen
    - wrapcheck
    - wsl
linters-settings:
  depguard:
    rules:
      main:
        list-mode: lax
        deny:
          - pkg: "invalidpkgs"
  errcheck:
    check-blank: true
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/edaniels/goutils)
  gofumpt:
    extra-rules: true
  govet:
    enable-all: true
    disable:
      - fieldalignment
  lll:
    line-length: 140
